In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from joblib import dump, load
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from itertools import cycle
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
import sklearn.metrics as metrics

import os
for dirname, _, filenames in os.walk('NSL-KDD'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

input/KDDTrain+.txt
input/KDDTest+.txt
input/KDDTrain+_20Percent.txt
input/KDDTest-21.txt

In [2]:
import pandas as pd
import numpy as np
import sys
import keras
import sklearn
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Embedding
from keras.layers import LSTM, SimpleRNN, GRU, Bidirectional, BatchNormalization,Convolution1D,MaxPooling1D, Reshape, GlobalAveragePooling1D
from keras.utils import to_categorical
from keras_self_attention import SeqSelfAttention
from keras.layers import Flatten
from keras.utils import plot_model
import sklearn.preprocessing
from sklearn import metrics
from scipy.stats import zscore
from keras.utils import get_file, plot_model
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import pydot_ng as pydot

print(pd.__version__)
print(np.__version__)
print(sys.version)
print(sklearn.__version__)

2023-02-28 18:43:31.341813: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 18:43:31.437317: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-28 18:43:31.452656: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-28 18:43:31.713514: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.6/lib64
2023-02-28 18:43:31.713553: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.6/lib64
2023-02-28 18:43:31.713556: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

1.5.0
1.23.5
3.9.12 (main, Jun  1 2022, 11:38:51)
[GCC 7.5.0]
1.1.2

In [53]:
#Loading training set into dataframe
df = pd.read_csv('NSL-KDD/KDDTrain+.txt', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [54]:
#Loading testing set into dataframe
qp = pd.read_csv('NSL-KDD/KDDTest+.txt', header=None)
qp.head()
print(qp.size)

969392

In [55]:
#Reset column names for training set
df.columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
'num_access_files', 'num_outbound_cmds', 'is_host_login',
'is_guest_login', 'count', 'srv_count', 'serror_rate',
'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
'dst_host_srv_count', 'dst_host_same_srv_rate','dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
'dst_host_srv_rerror_rate', 'subclass', 'difficulty_level']
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,subclass,difficulty_level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [56]:
#Reset column names for testing set
qp.columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
'num_access_files', 'num_outbound_cmds', 'is_host_login',
'is_guest_login', 'count', 'srv_count', 'serror_rate',
'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
'dst_host_srv_count', 'dst_host_same_srv_rate','dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
'dst_host_srv_rerror_rate', 'subclass', 'difficulty_level']
qp.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,subclass,difficulty_level
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
2,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.0,0.0,0.00,0.00,normal,21
3,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.0,0.0,0.00,0.00,saint,15
4,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.0,0.0,0.83,0.71,mscan,11

In [57]:
#accessing names of training columns
lst_names = df.columns # returns a list of column names
lst_names

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'subclass', 'difficulty_level'],
      dtype='object')

In [58]:
#accessing names of testing columns
testlst_names = qp.columns
testlst_names

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'subclass', 'difficulty_level'],
      dtype='object')

In [59]:
#Dropping the last columns of training set
df = df.drop('difficulty_level', 1) # we don't need it in this project
df.shape

/tmp/ipykernel_591975/129585363.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop('difficulty_level', 1) # we don't need it in this project

(125973, 42)

In [60]:
#Dropping the last columns of testing set
qp = qp.drop('difficulty_level', 1)
qp.shape

/tmp/ipykernel_591975/700357697.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  qp = qp.drop('difficulty_level', 1)

(22544, 42)

In [61]:
df.isnull().values.any()

False

In [62]:
qp.isnull().values.any()

False

In [63]:
#defining col list
cols = ['protocol_type','service','flag']
cols

['protocol_type', 'service', 'flag']

In [64]:
#One-hot encoding
def one_hot(df, cols):
    """
    @param df pandas DataFrame
    @param cols a list of columns to encode
    @return a DataFrame with one-hot encoding
    """
    for each in cols:
        dummies = pd.get_dummies(df[each], prefix=each, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(each, 1)
    return df

In [65]:
#Merging train and test data
combined_data = pd.concat([df,qp])

In [66]:
#Applying one hot encoding to combined data
combined_data = one_hot(combined_data,cols)

/tmp/ipykernel_591975/2521078246.py:11: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(each, 1)
/tmp/ipykernel_591975/2521078246.py:11: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(each, 1)
/tmp/ipykernel_591975/2521078246.py:11: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(each, 1)

In [67]:
#Function to min-max normalize
def normalize(df, cols):
    """
    @param df pandas DataFrame
    @param cols a list of columns to encode
    @return a DataFrame with normalized specified features
    """
    result = df.copy() # do not touch the original df
    for feature_name in cols:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        if max_value > min_value:
            result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [68]:
#Dropping subclass column for training set
tmp = combined_data.pop('subclass')

In [69]:
#Normalizing training set
new_train_df = normalize(combined_data,combined_data.columns)
new_train_df

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0.0,3.558064e-07,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.057999e-07,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.681203e-07,6.223962e-06,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.442067e-07,3.206260e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22539,0.0,5.753774e-07,2.542106e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22540,0.0,2.297162e-07,7.160648e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22541,0.0,3.952277e-05,6.346868e-06,0.0,0.0,0.0,0.019802,0.0,1.0,0.000134,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22542,0.0,3.043558e-08,3.206260e-08,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22543,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [70]:
#Fixing labels for training set
classlist = []
check1 = ("apache2","back","land","neptune","mailbomb","pod","processtable","smurf","teardrop","udpstorm","worm")
check2 = ("ipsweep","mscan","nmap","portsweep","saint","satan")
check3 = ("buffer_overflow","loadmodule","perl","ps","rootkit","sqlattack","xterm")
check4 = ("ftp_write","guess_passwd","httptunnel","imap","multihop","named","phf","sendmail","Snmpgetattack","spy","snmpguess","warezclient","warezmaster","xlock","xsnoop")

DoSCount=0
ProbeCount=0
U2RCount=0
R2LCount=0
NormalCount=0

for item in tmp:
    if item in check1:
        classlist.append("DoS")
        DoSCount=DoSCount+1
    elif item in check2:
        classlist.append("Probe")
        ProbeCount=ProbeCount+1
    elif item in check3:
        classlist.append("U2R")
        U2RCount=U2RCount+1
    elif item in check4:
        classlist.append("R2L")
        R2LCount=R2LCount+1
    else:
        classlist.append("Normal")
        NormalCount=NormalCount+1

In [71]:
DoSCount

53387

In [72]:
#Appending class column to training set
new_train_df["Class"] = classlist
new_train_df

/tmp/ipykernel_591975/803719109.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_train_df["Class"] = classlist

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH,Class
0,0.0,3.558064e-07,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Normal
1,0.0,1.057999e-07,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Normal
2,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,DoS
3,0.0,1.681203e-07,6.223962e-06,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Normal
4,0.0,1.442067e-07,3.206260e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22539,0.0,5.753774e-07,2.542106e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Normal
22540,0.0,2.297162e-07,7.160648e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Normal
22541,0.0,3.952277e-05,6.346868e-06,0.0,0.0,0.0,0.019802,0.0,1.0,0.000134,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,DoS
22542,0.0,3.043558e-08,3.206260e-08,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Normal
22543,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Probe

In [73]:
new_train_df["Class"].value_counts()

Normal    77232
DoS       53387
Probe     14077
R2L        3702
U2R         119
Name: Class, dtype: int64

In [74]:
new_train_df.isnull().values.any()

False

In [75]:
y_train=new_train_df["Class"]
y_train

0        Normal
1        Normal
2           DoS
3        Normal
4        Normal
          ...
22539    Normal
22540    Normal
22541       DoS
22542    Normal
22543     Probe
Name: Class, Length: 148517, dtype: object

In [76]:
y_train.isnull().values.any()

False

In [77]:
combined_data_X = new_train_df.drop('Class', 1)
combined_data_X

/tmp/ipykernel_591975/3277739742.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  combined_data_X = new_train_df.drop('Class', 1)

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0.0,3.558064e-07,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.057999e-07,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.681203e-07,6.223962e-06,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.442067e-07,3.206260e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22539,0.0,5.753774e-07,2.542106e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22540,0.0,2.297162e-07,7.160648e-07,0.0,0.0,0.0,0.000000,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22541,0.0,3.952277e-05,6.346868e-06,0.0,0.0,0.0,0.019802,0.0,1.0,0.000134,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22542,0.0,3.043558e-08,3.206260e-08,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22543,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
oos_pred = []

In [79]:
from sklearn.model_selection import StratifiedKFold

In [80]:
kfold = StratifiedKFold(n_splits=10,shuffle=True,random_state=42)
kfold.get_n_splits(combined_data_X,y_train)

10

In [82]:
#Bidirectional RNN
batch_size = 32
model = Sequential()
model.add(Convolution1D(64, kernel_size=64, padding="same",activation="relu",input_shape=(122, 1)))
model.add(MaxPooling1D(pool_size=(5)))
model.add(BatchNormalization())
model.add(Bidirectional(LSTM(64, return_sequences=True))) 
model.add(SeqSelfAttention(attention_activation='sigmoid'))  ##
model.add(Flatten()) 
model.add(Dropout(0.5))
model.add(Dense(5))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [83]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv1d_3 (Conv1D)           (None, 122, 64)           7872

 max_pooling1d_3 (MaxPooling  (None, 24, 64)           0
 1D)

 batch_normalization_3 (Batc  (None, 24, 64)           256
 hNormalization)

 bidirectional_3 (Bidirectio  (None, 24, 128)          66048
 nal)

 seq_self_attention_3 (SeqSe  (None, 24, 128)          8257
 lfAttention)

 flatten_3 (Flatten)         (None, 3072)              0

 dropout_3 (Dropout)         (None, 3072)              0

 dense_3 (Dense)             (None, 5)                 15365

 activation_3 (Activation)   (None, 5)                 0

=================================================================
Total params: 97,798
Trainable params: 97,670
Non-trainable params: 128
_________________________________________________________________

In [84]:
for train_index, test_index in kfold.split(combined_data_X,y_train):
    train_X, test_X = combined_data_X.iloc[train_index], combined_data_X.iloc[test_index]
    train_y, test_y = y_train.iloc[train_index], y_train.iloc[test_index]
    
    print("train index:",train_index)
    print("test index:",test_index)
    
    x_columns_train = new_train_df.columns.drop('Class')
    x_train_array = train_X[x_columns_train].values
    x_train_1=np.reshape(x_train_array, (x_train_array.shape[0], x_train_array.shape[1], 1))
    
    dummies = pd.get_dummies(train_y) # Classification
    outcomes = dummies.columns
    num_classes = len(outcomes)
    y_train_1 = dummies.values
    
    x_columns_test = new_train_df.columns.drop('Class')
    x_test_array = test_X[x_columns_test].values
    x_test_2=np.reshape(x_test_array, (x_test_array.shape[0], x_test_array.shape[1], 1))
    
    dummies_test = pd.get_dummies(test_y) # Classification
    outcomes_test = dummies_test.columns
    num_classes = len(outcomes_test)
    y_test_2 = dummies_test.values
    
    model.fit(x_train_1, y_train_1,validation_data=(x_test_2,y_test_2), epochs=50)

    pred = model.predict(x_test_2)
    pred = np.argmax(pred,axis=1)
    y_eval = np.argmax(y_test_2,axis=1)
    score = metrics.accuracy_score(y_eval, pred)
    oos_pred.append(score)
    print("Validation score: {}".format(score))

train index: [     0      2      3 ... 148514 148515 148516]
test index: [     1      7     18 ... 148506 148511 148513]
Epoch 1/10
4178/4178 [==============================] - 57s 13ms/step - loss: 0.0903 - accuracy: 0.9698 - val_loss: 0.0560 - val_accuracy: 0.9809
Epoch 2/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0547 - accuracy: 0.9805 - val_loss: 0.0436 - val_accuracy: 0.9836
Epoch 3/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0408 - accuracy: 0.9852 - val_loss: 0.0347 - val_accuracy: 0.9881
Epoch 4/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0352 - accuracy: 0.9872 - val_loss: 0.0372 - val_accuracy: 0.9874
Epoch 5/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0325 - accuracy: 0.9881 - val_loss: 0.0297 - val_accuracy: 0.9890
Epoch 6/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0302 - accuracy: 0.9892 - val_loss: 0.0290 - val_accuracy: 0.9892
Epoch 7/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0277 - accuracy: 0.9900 - val_loss: 0.0302 - val_accuracy: 0.9896
Epoch 8/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0265 - accuracy: 0.9903 - val_loss: 0.0347 - val_accuracy: 0.9871
Epoch 9/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0254 - accuracy: 0.9907 - val_loss: 0.0297 - val_accuracy: 0.9894
Epoch 10/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0245 - accuracy: 0.9908 - val_loss: 0.0272 - val_accuracy: 0.9908
465/465 [==============================] - 2s 4ms/step
Validation score: 0.9907756531106922
train index: [     0      1      2 ... 148514 148515 148516]
test index: [    12     15     17 ... 148456 148488 148504]
Epoch 1/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0238 - accuracy: 0.9914 - val_loss: 0.0243 - val_accuracy: 0.9899
Epoch 2/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0231 - accuracy: 0.9914 - val_loss: 0.0257 - val_accuracy: 0.9892
Epoch 3/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0217 - accuracy: 0.9920 - val_loss: 0.0217 - val_accuracy: 0.9917
Epoch 4/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0214 - accuracy: 0.9918 - val_loss: 0.0200 - val_accuracy: 0.9912
Epoch 5/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0211 - accuracy: 0.9920 - val_loss: 0.0207 - val_accuracy: 0.9925
Epoch 6/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0201 - accuracy: 0.9924 - val_loss: 0.0227 - val_accuracy: 0.9925
Epoch 7/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0197 - accuracy: 0.9928 - val_loss: 0.0223 - val_accuracy: 0.9929
Epoch 8/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0196 - accuracy: 0.9925 - val_loss: 0.0207 - val_accuracy: 0.9921
Epoch 9/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0192 - accuracy: 0.9925 - val_loss: 0.0214 - val_accuracy: 0.9923
Epoch 10/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0190 - accuracy: 0.9928 - val_loss: 0.0214 - val_accuracy: 0.9931
465/465 [==============================] - 0s 917us/step
Validation score: 0.9931322380824131
train index: [     0      1      2 ... 148513 148514 148516]
test index: [    16     26     38 ... 148490 148499 148515]
Epoch 1/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0186 - accuracy: 0.9929 - val_loss: 0.0193 - val_accuracy: 0.9921
Epoch 2/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0179 - accuracy: 0.9931 - val_loss: 0.0188 - val_accuracy: 0.9933
Epoch 3/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0175 - accuracy: 0.9933 - val_loss: 0.0188 - val_accuracy: 0.9935
Epoch 4/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0170 - accuracy: 0.9936 - val_loss: 0.0200 - val_accuracy: 0.9925
Epoch 5/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0170 - accuracy: 0.9935 - val_loss: 0.0206 - val_accuracy: 0.9922
Epoch 6/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0169 - accuracy: 0.9935 - val_loss: 0.0214 - val_accuracy: 0.9928
Epoch 7/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0166 - accuracy: 0.9937 - val_loss: 0.0217 - val_accuracy: 0.9924
Epoch 8/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0162 - accuracy: 0.9935 - val_loss: 0.0198 - val_accuracy: 0.9931
Epoch 9/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0161 - accuracy: 0.9939 - val_loss: 0.0211 - val_accuracy: 0.9930
Epoch 10/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0157 - accuracy: 0.9940 - val_loss: 0.0200 - val_accuracy: 0.9943
465/465 [==============================] - 2s 4ms/step
Validation score: 0.9942768650686776
train index: [     0      1      2 ... 148514 148515 148516]
test index: [    10     42     44 ... 148465 148474 148507]
Epoch 1/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0166 - accuracy: 0.9940 - val_loss: 0.0135 - val_accuracy: 0.9943
Epoch 2/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0163 - accuracy: 0.9940 - val_loss: 0.0125 - val_accuracy: 0.9959
Epoch 3/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0161 - accuracy: 0.9939 - val_loss: 0.0129 - val_accuracy: 0.9943
Epoch 4/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0152 - accuracy: 0.9942 - val_loss: 0.0123 - val_accuracy: 0.9954
Epoch 5/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0149 - accuracy: 0.9942 - val_loss: 0.0150 - val_accuracy: 0.9950
Epoch 6/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0152 - accuracy: 0.9943 - val_loss: 0.0154 - val_accuracy: 0.9943
Epoch 7/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0148 - accuracy: 0.9943 - val_loss: 0.0129 - val_accuracy: 0.9947
Epoch 8/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0147 - accuracy: 0.9943 - val_loss: 0.0124 - val_accuracy: 0.9958
Epoch 9/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0150 - accuracy: 0.9942 - val_loss: 0.0134 - val_accuracy: 0.9949
Epoch 10/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0147 - accuracy: 0.9944 - val_loss: 0.0138 - val_accuracy: 0.9943
465/465 [==============================] - 0s 1ms/step
Validation score: 0.9943441960678696
train index: [     0      1      2 ... 148514 148515 148516]
test index: [    14     23     34 ... 148477 148498 148505]
Epoch 1/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0143 - accuracy: 0.9949 - val_loss: 0.0129 - val_accuracy: 0.9950
Epoch 2/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0142 - accuracy: 0.9946 - val_loss: 0.0144 - val_accuracy: 0.9947
Epoch 3/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0145 - accuracy: 0.9945 - val_loss: 0.0174 - val_accuracy: 0.9938
Epoch 4/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0141 - accuracy: 0.9948 - val_loss: 0.0153 - val_accuracy: 0.9941
Epoch 5/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0142 - accuracy: 0.9947 - val_loss: 0.0147 - val_accuracy: 0.9944
Epoch 6/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0138 - accuracy: 0.9948 - val_loss: 0.0169 - val_accuracy: 0.9938
Epoch 7/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0137 - accuracy: 0.9948 - val_loss: 0.0153 - val_accuracy: 0.9950
Epoch 8/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0136 - accuracy: 0.9947 - val_loss: 0.0153 - val_accuracy: 0.9942
Epoch 9/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0135 - accuracy: 0.9948 - val_loss: 0.0164 - val_accuracy: 0.9929
Epoch 10/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0129 - accuracy: 0.9950 - val_loss: 0.0181 - val_accuracy: 0.9931
465/465 [==============================] - 1s 1ms/step
Validation score: 0.9930649070832211
train index: [     0      1      2 ... 148513 148515 148516]
test index: [     6     20     36 ... 148509 148510 148514]
Epoch 1/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0142 - accuracy: 0.9946 - val_loss: 0.0121 - val_accuracy: 0.9959
Epoch 2/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0135 - accuracy: 0.9948 - val_loss: 0.0126 - val_accuracy: 0.9954
Epoch 3/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0133 - accuracy: 0.9950 - val_loss: 0.0129 - val_accuracy: 0.9952
Epoch 4/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0134 - accuracy: 0.9949 - val_loss: 0.0136 - val_accuracy: 0.9948
Epoch 5/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0129 - accuracy: 0.9949 - val_loss: 0.0171 - val_accuracy: 0.9937
Epoch 6/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0135 - accuracy: 0.9949 - val_loss: 0.0142 - val_accuracy: 0.9942
Epoch 7/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0122 - accuracy: 0.9951 - val_loss: 0.0163 - val_accuracy: 0.9943
Epoch 8/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0128 - accuracy: 0.9949 - val_loss: 0.0148 - val_accuracy: 0.9943
Epoch 9/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0127 - accuracy: 0.9953 - val_loss: 0.0134 - val_accuracy: 0.9952
Epoch 10/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0125 - accuracy: 0.9950 - val_loss: 0.0131 - val_accuracy: 0.9949
465/465 [==============================] - 0s 994us/step
Validation score: 0.9948828440614059
train index: [     0      1      2 ... 148514 148515 148516]
test index: [     4     22     30 ... 148486 148492 148497]
Epoch 1/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0131 - accuracy: 0.9949 - val_loss: 0.0115 - val_accuracy: 0.9956
Epoch 2/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0126 - accuracy: 0.9952 - val_loss: 0.0111 - val_accuracy: 0.9956
Epoch 3/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0126 - accuracy: 0.9951 - val_loss: 0.0156 - val_accuracy: 0.9947
Epoch 4/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0122 - accuracy: 0.9953 - val_loss: 0.0125 - val_accuracy: 0.9952
Epoch 5/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0121 - accuracy: 0.9953 - val_loss: 0.0119 - val_accuracy: 0.9945
Epoch 6/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0119 - accuracy: 0.9954 - val_loss: 0.0119 - val_accuracy: 0.9952
Epoch 7/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0120 - accuracy: 0.9953 - val_loss: 0.0118 - val_accuracy: 0.9958
Epoch 8/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0123 - accuracy: 0.9953 - val_loss: 0.0125 - val_accuracy: 0.9955
Epoch 9/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0118 - accuracy: 0.9953 - val_loss: 0.0132 - val_accuracy: 0.9945
Epoch 10/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0117 - accuracy: 0.9955 - val_loss: 0.0162 - val_accuracy: 0.9937
465/465 [==============================] - 2s 3ms/step
Validation score: 0.9936708860759493
train index: [     1      2      4 ... 148514 148515 148516]
test index: [     0      3      9 ... 148500 148501 148508]
Epoch 1/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0122 - accuracy: 0.9953 - val_loss: 0.0127 - val_accuracy: 0.9952
Epoch 2/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0118 - accuracy: 0.9955 - val_loss: 0.0128 - val_accuracy: 0.9953
Epoch 3/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0119 - accuracy: 0.9950 - val_loss: 0.0123 - val_accuracy: 0.9958
Epoch 4/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0115 - accuracy: 0.9955 - val_loss: 0.0141 - val_accuracy: 0.9943
Epoch 5/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0117 - accuracy: 0.9954 - val_loss: 0.0155 - val_accuracy: 0.9937
Epoch 6/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0118 - accuracy: 0.9954 - val_loss: 0.0128 - val_accuracy: 0.9955
Epoch 7/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0115 - accuracy: 0.9954 - val_loss: 0.0131 - val_accuracy: 0.9947
Epoch 8/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0115 - accuracy: 0.9956 - val_loss: 0.0134 - val_accuracy: 0.9954
Epoch 9/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0118 - accuracy: 0.9954 - val_loss: 0.0137 - val_accuracy: 0.9951
Epoch 10/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0117 - accuracy: 0.9955 - val_loss: 0.0135 - val_accuracy: 0.9951
465/465 [==============================] - 2s 4ms/step
Validation score: 0.9950845060938658
train index: [     0      1      2 ... 148514 148515 148516]
test index: [     5     11     13 ... 148483 148489 148491]
Epoch 1/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0116 - accuracy: 0.9954 - val_loss: 0.0112 - val_accuracy: 0.9954
Epoch 2/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0115 - accuracy: 0.9953 - val_loss: 0.0110 - val_accuracy: 0.9959
Epoch 3/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0116 - accuracy: 0.9953 - val_loss: 0.0107 - val_accuracy: 0.9961
Epoch 4/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0113 - accuracy: 0.9958 - val_loss: 0.0120 - val_accuracy: 0.9952
Epoch 5/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0110 - accuracy: 0.9956 - val_loss: 0.0118 - val_accuracy: 0.9956
Epoch 6/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0109 - accuracy: 0.9955 - val_loss: 0.0128 - val_accuracy: 0.9948
Epoch 7/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0113 - accuracy: 0.9957 - val_loss: 0.0114 - val_accuracy: 0.9954
Epoch 8/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0112 - accuracy: 0.9957 - val_loss: 0.0126 - val_accuracy: 0.9954
Epoch 9/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0109 - accuracy: 0.9956 - val_loss: 0.0138 - val_accuracy: 0.9951
Epoch 10/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0108 - accuracy: 0.9957 - val_loss: 0.0140 - val_accuracy: 0.9949
465/465 [==============================] - 0s 912us/step
Validation score: 0.9949498350279442
train index: [     0      1      3 ... 148513 148514 148515]
test index: [     2      8     25 ... 148464 148512 148516]
Epoch 1/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0115 - accuracy: 0.9955 - val_loss: 0.0122 - val_accuracy: 0.9952
Epoch 2/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0105 - accuracy: 0.9959 - val_loss: 0.0136 - val_accuracy: 0.9943
Epoch 3/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0108 - accuracy: 0.9957 - val_loss: 0.0123 - val_accuracy: 0.9950
Epoch 4/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0108 - accuracy: 0.9958 - val_loss: 0.0126 - val_accuracy: 0.9950
Epoch 5/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0105 - accuracy: 0.9958 - val_loss: 0.0118 - val_accuracy: 0.9950
Epoch 6/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0107 - accuracy: 0.9958 - val_loss: 0.0123 - val_accuracy: 0.9946
Epoch 7/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0105 - accuracy: 0.9957 - val_loss: 0.0155 - val_accuracy: 0.9943
Epoch 8/10
4178/4178 [==============================] - 55s 13ms/step - loss: 0.0106 - accuracy: 0.9959 - val_loss: 0.0138 - val_accuracy: 0.9952
Epoch 9/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0103 - accuracy: 0.9960 - val_loss: 0.0131 - val_accuracy: 0.9947
Epoch 10/10
4178/4178 [==============================] - 56s 13ms/step - loss: 0.0104 - accuracy: 0.9957 - val_loss: 0.0145 - val_accuracy: 0.9951
465/465 [==============================] - 0s 1ms/step
Validation score: 0.9950845060938658

In [85]:
oos_pred

[0.9907756531106922,
 0.9931322380824131,
 0.9942768650686776,
 0.9943441960678696,
 0.9930649070832211,
 0.9948828440614059,
 0.9936708860759493,
 0.9950845060938658,
 0.9949498350279442,
 0.9950845060938658]

In [86]:
import h5py
model.save("model10.h5")

In [87]:
dummies_test.columns

Index(['DoS', 'Normal', 'Probe', 'R2L', 'U2R'], dtype='object')

In [88]:
test_y.value_counts()

Normal    7723
DoS       5338
Probe     1407
R2L        371
U2R         12
Name: Class, dtype: int64

In [89]:
from sklearn.metrics import confusion_matrix

In [90]:
cm = confusion_matrix(y_eval, pred, labels=[0,1,2,3,4])

In [91]:
print(cm)

[[5334    4    0    0    0]
 [   3 7699   13    8    0]
 [   0    8 1399    0    0]
 [   0   30    0  339    2]
 [   0    3    0    2    7]]

In [19]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  0